### ISSUE TITLE
Broken local reference in #use-case-generate-vector-features

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/HTML-Map-Element-UseCases-Requirements#185]
Missing link in [#use-case-generate-vector-features](https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#use-case-generate-vector-features):

> [missing: content author use case](https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#) covers the use of existing vector data, in standard geographic file formats. However, a web app developer may want to dynamically generate vector shapes from data. For example, to implement a feature allowing users to draw new shapes on the map, the developer needs to convert the selected points into a new polygon feature.

I'm not sure what author use case is that the link should point to, perhaps [#use-case-poly-features](https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#use-case-poly-features)?

**Comment by AmeliaBR** [comment]
Ah, no, that was me intentionally reminding myself to add a matching Use Case that isn't yet in the draft. Adding lots of use cases around data file formats is on my own To-Do. (Started it in July/August, but then stuff happened…)

**Comment by AmeliaBR** [comment]
Anyway, sorry for the extra ReSpec error in the meantime. I'll leave this issue open as an extra reminder until we get it fixed!

**Comment by Malvoz** [comment]
Fixed by https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/pull/198.
