### ISSUE TITLE
Configure API tokens to work with maps4html.org

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/HTML-Map-Element-UseCases-Requirements#201]
As we're now using the custom domain https://maps4html.org, configuration is needed for it to work with API tokens, for the example pages.

**Comment by NickFitz** [comment]
As I recall, the Google, Bing, and Apple keys are from my accounts, so I’ll see about generating new ones for those or adding the new domain to the existing ones. @AmeliaBR I think the Mapbox key was changed to one you configured? Anyway, if needs be, I can also set up a suitable key on my Mapbox account.

**Comment by AmeliaBR** [comment]
Ah, ooops. When @prushforth suggested switching over to the custom domain, I forgot about the impact on API keys!

@NickFitz if you want to do them all in one go, that'd be great. If you have any troubles, let me know and I'll see what I can set up.

**Comment by Malvoz** [comment]
I'd love to see this resolved as soon as possible, I've been intending to document accessibility issues (privately for now) found in the web maps for each web map tool, and as such rely on the examples to work.

**Comment by AmeliaBR** [comment]
Sorry @Malvoz, looks like we dropped the ball here about who was going to take the fix.

@NickFitz are you able to make these changes in the next couple days, or should I take over?

**Comment by AmeliaBR** [comment]
OK, that was more than a few days, but I've updated both the TomTom and MapBox tokens, which were associated with my account.

It looks like MapKit is the only one still broken (at least for the simple examples). @NickFitz, will you be able to get to that?

**Comment by NickFitz** [comment]
@AmeliaBR Apologies, I’ve been laid low with some virus for a couple of weeks. I’ll see about updating the MapKit tokens ASAP.
