### ISSUE TITLE
Migrate from Travis CI to Github Actions

### ISSUE THREAD

**Issue by nchan0154** [Maps4HTML/HTML-Map-Element-UseCases-Requirements#245]
I think I've addressed this with a Github Action! It would be good to merge some of the small lingering PRs to make sure this is functioning as desired before we remove Travis and close this one out. :)

**Comment by prushforth** [comment]
Huh too bad I disabled travis in January.  Sorry I didn't realize you had this job running.  Does the action do what you want?  Thanks for taking care of it!

**Comment by AmeliaBR** [comment]
OK, I merged a couple of @Malvoz's pending PR fixes (which should have been merged long ago!) & it looks like the builds got pushed to Github Pages fine.

The Github Actions page is a little confusing, though. The table has a column for the status of each run, but nothing is showing as success (or any other status). Maybe there's an extra line in the YAML file for setting that value?
https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/actions/workflows/deploy.yml

Either way, it's probably safe to remove the Travis YAML now.

**Comment by nchan0154** [comment]
Hmm, from what I can tell, the status select seems to be a filter, not a column header, the way to tell the status is via the check/cross icon next to the title.  Certainly a bit of confusing UI there. Anyway, I've removed the Travis file, so we can probably close this one out!

**Comment by AmeliaBR** [comment]
Ah, you're right. Similar to the filters on an issue list.

I'm not sure why my brain didn't notice the checkmarks yesterday when I was trying to figure out if the builds had completed successfully, but anyway, glad to have someone else looking at it.
