### ISSUE TITLE
Help Wanted! Paid freelance gig for researchers / writers / front-end web devs

### ISSUE THREAD

**Issue by AmeliaBR** [Maps4HTML/HTML-Map-Element-UseCases-Requirements#46]
_This is not really an issue, but if you're watching issues on this repo then this is relevant to your interests!_

I'm Amelia, the current editor of the [Use Cases and Requirements for Standardizing Web Maps](https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/) report.  

I'd like to get this report complete & polished. But I haven't been able to put as many hours in as I'd like, given the scope & complexity of “maps on the web”!

Therefore, I'm looking to hire one or more part-time contributors to help with the research, writing, and code.  My work is paid for under a contract with [Natural Resources Canada's Geomatics group](https://www.nrcan.gc.ca/earth-sciences/geomatics/10776), under the supervision of @prushforth.  But to be clear: you'd be contracting to me, not NRCan.

Job description below.  Leave a comment on this issue if you have any general questions that would be of interest to other applicants.  If you have specific questions, or to apply, please send me an email directly, to amelia.bellamy.royds@gmail.com

________________________

## Tasks

These are the tasks I need help with. You do not have to be able to do all of them, we can delegate different tasks to different people based on skills & time available.

- Draft text summarizing the various use cases & capabilities. Think of new ones.

- Create example pages showing how the [reference JS tools](https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#js-examples) can be used to meet the various use cases in the report.

- Summarize the support level & limitations of each of tool's implementation of each capability.

- Compile information about related web standards & how they are similar to / different from the web mapping use cases.

- Discuss potential conclusions for each section, in particular how the different technological capabilities intersect with the various [guiding principles for web standards](https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#principles).

- Respond to and help organize issue reports.

- Complete the pre-processing scripts to generate support tables and summaries of conclusions from the tagged markup in each section.

Other tasks may arise over the course of the contract.

## Expected skills & aptitudes

- Able to communicate in basic written English. Don't worry if you're not perfectly fluent; other people can edit the text if you can contribute the information.

- Able to work without supervision & manage your own time, but also able to recognize when to ask for help or consult with colleagues.

- Good attention to detail & able to make organized notes.

- Able to break down complex problems into independent concepts, and to identify shared building blocks across different applications.

- Familiar with semantic HTML (enough to write the report in HTML markup).

- Familiar with git & GitHub (enough to make logical commits, use branches and PRs, and work with issues).

- Familiar with front-end JavaScript (enough to work with the reference JS tools & maybe help with the report pre-processing script).

## Additional skills that are strong assets

- Previous experience with web map tools & frameworks.

- Familiarity with geographic data servers (GIS) and map data formats.

- Experience with web accessibility testing.

- Experience with web standards processes, web platform testing, or web browser teams.

## Terms of the contract

- All work for this project is on an on-demand basis, subject to agreement by both parties (myself as the purchaser & you as the contractor) on individual tasks.  An agreement to complete a task will include an agreement on its deadlines and the maximum hours that should be billed (both of which can be changed by later agreement).

- There is no guarantee about how much work will be required. The contractor hired does not need to guarantee availability.  Both sides agree to notify the other as soon as possible if there is a change in the expected work requirements or work availability.

- The work will be invoiced on an hourly basis, at a rate of 95 CAD (Canadian dollars) per hour.

- Invoices should be sent monthly, by the 5th day of the month for the previous month's work, and will be paid (by electronic transfer method to be determined based on the contractor's country & preferences) within 45 days.

- The contractor agrees to keep records of time spent on each task & to provide them to the purchaser & to Natural Resources Canada if requested.

- The contractor must be able to join the [Maps for HTML community group](https://www.w3.org/community/maps4html/) and agree to the [W3C Community Contributor License Agreement (CLA)](https://www.w3.org/community/about/agreements/cla/) as an individual, or as a representative of a group that does not prohibit this type of freelance contracting.

- The contractor must have or be able to create a GitHub account.

- The contractor will submit work via GitHub issues and pull requests where appropriate, or by email otherwise.  Discussion of the work will happen by these methods or by teleconference/video conference as needed.

- All intellectual property created under the contract will belong to Natural Resources Canada (NRCan), but with the understanding that it will be contributed to the Maps for HTML community group or other web standards groups, under the terms of the [Open Government Licence - Canada](https://open.canada.ca/en/open-government-licence-canada).  The contractor agrees to keep copies of all their work & to submit it as requested, according to [the IP conditions on the NRCan contract](https://buyandsell.gc.ca/policy-and-guidelines/standard-acquisition-clauses-and-conditions-manual/4/4007/3).

- Other [general conditions](https://buyandsell.gc.ca/policy-and-guidelines/standard-acquisition-clauses-and-conditions-manual/3/2035/17) apply to the purchaser's contract with Natural Resources Canada; the contractor in this sub-contract must agree to meet those requirements where applicable.  Specifically, please mention in your application if any of these situations apply:

  * You are a resident or citizen of a [country against which Canada has economic sanctions](https://www.international.gc.ca/world-monde/international_relations-relations_internationales/sanctions/current-actuelles.aspx?lang=eng). Note: most of those sanctions only apply to military contracts, but we'll need to follow up and make sure there are no problems.
  * You are a non-Canadian in Canada; you'll need a work visa or a student visa that allows part-time contract work.
  * You are a former Canadian public servant who is receiving a pension or who received a severance payment.

**Comment by AmeliaBR** [comment]
Update: We have two new contributors to the report! Welcome @NickFitz (already landed [his first PR](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/pull/47)!) and @nchan0154.

@prushforth, can you set them up with enough permissions to add tags to issues? 

I'll leave this post open, since there may be more work to go around over the next few months.

**Comment by prushforth** [comment]
I've invited @NickFitz as a contributor, and @nchan0154 as a member. When she joins the [community group](https://www.w3.org/community/maps4html/participants) I'll assign write permissions to her.

**Comment by nchan0154** [comment]
Thank you for your patience with me while I wrapped up a project this week! I've joined the community group and am excited to start working with you all on this :)

**Comment by prushforth** [comment]
@nchan0154 No worries! Thanks for your help on the project. I've add you to contributors...

**Comment by Malvoz** [comment]
Since this issue is open I presume you're still looking to hire, maybe consider [pinning](https://help.github.com/en/articles/pinning-an-issue-to-your-repository) this issue for more exposure?

**Comment by AmeliaBR** [comment]
Thanks for the tip about pinning issue, @Malvoz! PS, do get in touch if you want to formalize your contributions — there's plenty to do & you've been very helpful so far.
