### ISSUE TITLE
Use Case: Fallback for browsers that don't support <new-map-element>

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/HTML-Map-Element-UseCases-Requirements#52]
This is a stub. I add it because of the suggestion to rename this [repository](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/45), which I would support (seems straightforward to do, although we would need to find links that point here and update them).

In any case, we need to talk about what the fallback scenarios and recommended approach will be for future web maps in HTML, no matter what the name(s) of the elements.  Enhancing existing semantics seems like the right approach.  I think `<picture>` may have demonstrated some good markup design / fallback behaviour worth copying/ using as a pattern.

**Comment by Malvoz** [comment]
> [repository](https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/52#45)

That link isn't valid (https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/45).

**Comment by prushforth** [comment]
Fixed, ty

**Comment by prushforth** [comment]
Sure, let discussion happen there.
