### ISSUE TITLE
Capability: Add a control to a map

### ISSUE THREAD

**Issue by NickFitz** [Maps4HTML/HTML-Map-Element-UseCases-Requirements#58]
This issue is for discussion of [the required API capability “Add a control to a map”](https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#capability-add-control-map).

**Comment by AmeliaBR** [comment]
Is this intended to represent the ability to "turn on" a default control, or the ability to add custom widgets?

**Comment by NickFitz** [comment]
As adding and removing a control is really part of whatever support an implementation provides for custom controls, I'm of the opinion this capability and https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/59 should be removed. I'll do so on a separate branch so it doesn't get bundled in with other pull requests.

**Comment by Malvoz** [comment]
Capability removed in #217.
