### ISSUE TITLE
Capability: Remove a control from a map

### ISSUE THREAD

**Issue by NickFitz** [Maps4HTML/HTML-Map-Element-UseCases-Requirements#59]
This issue is for discussion of [the required API capability “Remove a control from a map”](https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#capability-remove-control-map).

**Comment by NickFitz** [comment]
As adding and removing a control is really part of whatever support an implementation provides for custom controls, I'm of the opinion this capability and https://github.com/Maps4HTML/HTML-Map-Element-UseCases-Requirements/issues/58 should be removed. I'll do so on a separate branch so it doesn't get bundled in with other pull requests.

**Comment by Malvoz** [comment]
Capability removed in #217.
