### ISSUE TITLE
Capability: Reset the bearing of a map

### ISSUE THREAD

**Issue by NickFitz** [Maps4HTML/HTML-Map-Element-UseCases-Requirements#73]
This issue is for discussion of [the required API capability “Reset the bearing of a map”](https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#capability-reset-bearing-map).

**Comment by AmeliaBR** [comment]
How is this different from "Change the bearing" (#72), at an API level?

**Comment by AmeliaBR** [comment]
Merged into #72
