### ISSUE TITLE
Use Case: Specify a data source for a map

### ISSUE THREAD

**Issue by NickFitz** [Maps4HTML/HTML-Map-Element-UseCases-Requirements#85]
This issue is for discussion of [the use case “Specify a data source for a map”](https://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#use-case-specify-data-source-map), its examples & list of required capabilities.

**Comment by prushforth** [comment]
The link doesn't go to a section in the report. Hopefully these will be added, although adding a description of each will need to be crowd sourced.

**Comment by prushforth** [comment]
MapML [proposal](https://github.com/Maps4HTML/HTML-Map-Element/issues/18#issuecomment-502376790)

**Comment by AmeliaBR** [comment]
Merged into #38.
