### ISSUE TITLE
Broken citation link: Geolocation APIs

### ISSUE THREAD

**Issue by AmeliaBR** [Maps4HTML/HTML-Map-Element-UseCases-Requirements#86]
ReSpec can no longer find the auto-link citation data for the "geolocation api" and "geolocation sensor api".  Need to track down what's changed & update.

**Comment by AmeliaBR** [comment]
Looks like this is a ReSpec bug, not us: https://github.com/w3c/respec/issues/2394

We could remove the errors by switching to the `[[[short-name]]]` syntax, but that auto-fills a much wordier version of one of the titles; I'd prefer to keep it as is & hope that the ReSpec bug gets tidied up.  The references are correctly being linked, it's only the error that's a problem.

**Comment by marcoscaceres** [comment]
Unfortunately, we made a breaking change in ReSpec without realizing it :( To fix this, you will need to add `data-no-xref=""` to the ones that are causing issues.
